# version: '3.7'

services:
  db:
    image: postgres:16
    container_name: shrotly_db
    restart: always
    env_file:
      - .env_prod
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image:  redis:7
    container_name: shrotly_redis

  shortly:
    build:
      context: .
    container_name: shrotly_app
    restart: always
    env_file:
      - .env_prod
    depends_on:
      - db
      - redis
    command: ["/shortly_links/docker/app.sh"]
    ports:
      - '8000:8000'

  celery:
    build:
      context: .
    container_name: shortly_celery
    env_file:
      - .env_prod
    depends_on:
      - redis
    command: ["/shortly_links/docker/celery.sh"]

  prometheus:
    image: prom/prometheus:v2.43.0
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheusdata:/prometheus
    restart: unless-stopped
    ports:
      - 9090:9090

  grafana:
    image: grafana/grafana:9.4.7
    container_name: grafana
    volumes:
      - grafanadata:/var/lib/grafana
    restart: unless-stopped
    ports:
      - 3000:3000

volumes:
  postgres_data:
  grafanadata:
  prometheusdata:
    